# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('ccp', 'CCP'), ('tr', 'TR')], default='', max_length=20)),
                ('member', models.CharField(max_length=20)),
                ('bic_code', models.CharField(max_length=20)),
                ('lei_code', models.CharField(max_length=20)),
                ('member_name', models.CharField(max_length=20)),
                ('login_id', models.CharField(max_length=20)),
                ('login_pass', models.CharField(max_length=20)),
                ('irs_won', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3)),
                ('irs_usd', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3)),
                ('ndf', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('pro_fx', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UrlMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('ccp', 'CCP'), ('tr', 'TR')], max_length=20)),
                ('product', models.CharField(choices=[('iw', 'IRS-WON'), ('iu', 'IRS-USD'), ('nu', 'NDF-USD')], max_length=20)),
                ('member', models.CharField(max_length=20)),
                ('process', models.CharField(choices=[('list', 'LIST'), ('data', 'DATA')], max_length=20)),
                ('item', models.CharField(blank=True, choices=[('all', 'ALL'), (None, 'None')], max_length=20)),
                ('seq', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
