# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 02:20
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_state', models.CharField(blank=True, max_length=3)),
                ('market', models.CharField(choices=[('ccp', 'CCP'), ('tr', 'TR')], default='', max_length=20)),
                ('member', models.CharField(blank=True, max_length=20)),
                ('bic_code', models.CharField(blank=True, max_length=20)),
                ('lei_code', models.CharField(blank=True, max_length=20)),
                ('member_name', models.CharField(blank=True, max_length=50)),
                ('login_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('login_pass', models.CharField(blank=True, max_length=20)),
                ('irs_won', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True)),
                ('irs_usd', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True)),
                ('ndf', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True)),
                ('pro_fx', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IFD_POST_DATA_M_',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.CharField(choices=[('ccp', 'CCP'), ('tr', 'TR')], max_length=20)),
                ('product', models.CharField(choices=[('irs-won', 'IRS-WON'), ('irs-usd', 'IRS-USD'), ('ndf', 'NDF')], max_length=20)),
                ('member', models.CharField(max_length=20)),
                ('item', models.CharField(blank=True, choices=[('tcpmih00101', 'TCPMIH00101'), ('tcpmih00102', 'TCPMIH00102'), ('tcpmih00103', 'TCPMIH00103'), ('tcpmih00104', 'TCPMIH00104'), ('tcpmih00105', 'TCPMIH00105'), ('tcpmih00106', 'TCPMIH00106'), ('tcpmih00107', 'TCPMIH00107'), ('tcpmir00101', 'TCPMIR00101')], max_length=20, null=True)),
                ('item_group', models.CharField(blank=True, choices=[('clearing', 'CLEARING'), ('settlement', 'SETTLEMENT'), ('risk', 'RISK'), ('pricing', 'PRICING'), ('rds', 'RDS'), ('post', 'POST')], max_length=20, null=True)),
                ('item_seq', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_state', models.CharField(max_length=3)),
                ('market', models.CharField(choices=[('ccp', 'CCP'), ('tr', 'TR')], default='', max_length=20)),
                ('member', models.CharField(max_length=20)),
                ('bic_code', models.CharField(max_length=20)),
                ('lei_code', models.CharField(max_length=20)),
                ('member_name', models.CharField(max_length=50)),
                ('login_id', models.CharField(max_length=20)),
                ('login_pass', models.CharField(max_length=20)),
                ('irs_won', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True)),
                ('irs_usd', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True)),
                ('ndf', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True)),
                ('pro_fx', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Total_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.CharField(choices=[('ccp', 'CCP'), ('tr', 'TR')], default='', max_length=20)),
                ('member', models.CharField(max_length=20)),
                ('bic_code', models.CharField(max_length=20)),
                ('lei_code', models.CharField(max_length=20)),
                ('member_name', models.CharField(max_length=50)),
                ('login_id', models.CharField(max_length=20)),
                ('login_pass', models.CharField(max_length=20)),
                ('irs_won', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True)),
                ('irs_usd', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True)),
                ('ndf', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True)),
                ('pro_fx', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TOTAL_SEQ_INFO_M_',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.CharField(choices=[('ccp', 'CCP'), ('tr', 'TR')], max_length=20)),
                ('product', models.CharField(choices=[('irs-won', 'IRS-WON'), ('irs-usd', 'IRS-USD'), ('ndf', 'NDF')], max_length=20)),
                ('member', models.CharField(max_length=20)),
                ('item', models.CharField(blank=True, choices=[('tcpmih00101', 'TCPMIH00101'), ('tcpmih00102', 'TCPMIH00102'), ('tcpmih00103', 'TCPMIH00103'), ('tcpmih00104', 'TCPMIH00104'), ('tcpmih00105', 'TCPMIH00105'), ('tcpmih00106', 'TCPMIH00106'), ('tcpmih00107', 'TCPMIH00107'), ('tcpmir00101', 'TCPMIR00101')], max_length=20, null=True)),
                ('item_group', models.CharField(blank=True, choices=[('clearing', 'CLEARING'), ('settlement', 'SETTLEMENT'), ('risk', 'RISK'), ('pricing', 'PRICING'), ('rds', 'RDS'), ('post', 'POST')], max_length=20, null=True)),
                ('item_seq', models.CharField(max_length=20)),
                ('fmtoa_seq', models.CharField(max_length=20)),
                ('fatob_seq', models.CharField(max_length=20)),
                ('end_bit', models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrCodeInfo_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.CharField(choices=[('ccp', 'CCP'), ('tr', 'TR')], default='', max_length=20)),
                ('product', models.CharField(choices=[('irs-won', 'IRS-WON'), ('irs-usd', 'IRS-USD'), ('ndf', 'NDF')], default='', max_length=20)),
                ('member', models.CharField(max_length=20)),
                ('item', models.CharField(choices=[('tcpmih00101', 'TCPMIH00101'), ('tcpmih00102', 'TCPMIH00102'), ('tcpmih00103', 'TCPMIH00103'), ('tcpmih00104', 'TCPMIH00104'), ('tcpmih00105', 'TCPMIH00105'), ('tcpmih00106', 'TCPMIH00106'), ('tcpmih00107', 'TCPMIH00107'), ('tcpmir00101', 'TCPMIR00101')], default='', max_length=20)),
                ('item_group', models.CharField(choices=[('clearing', 'CLEARING'), ('settlement', 'SETTLEMENT'), ('risk', 'RISK'), ('pricing', 'PRICING'), ('rds', 'RDS'), ('post', 'POST')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UrlMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('ccp', 'CCP'), ('tr', 'TR')], max_length=20)),
                ('product', models.CharField(choices=[('irs-won', 'IRS-WON'), ('irs-usd', 'IRS-USD'), ('ndf', 'NDF')], max_length=20)),
                ('member', models.CharField(max_length=20)),
                ('process', models.CharField(choices=[('list', 'LIST'), ('data', 'DATA')], max_length=20)),
                ('item', models.CharField(blank=True, choices=[('tcpmih00101', 'TCPMIH00101'), ('tcpmih00102', 'TCPMIH00102'), ('tcpmih00103', 'TCPMIH00103'), ('tcpmih00104', 'TCPMIH00104'), ('tcpmih00105', 'TCPMIH00105'), ('tcpmih00106', 'TCPMIH00106'), ('tcpmih00107', 'TCPMIH00107'), ('tcpmir00101', 'TCPMIR00101')], max_length=20, null=True)),
                ('item_group', models.CharField(choices=[('clearing', 'CLEARING'), ('settlement', 'SETTLEMENT'), ('risk', 'RISK'), ('pricing', 'PRICING'), ('rds', 'RDS'), ('post', 'POST')], default='', max_length=20)),
                ('item_seq', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
