# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=20)),
                ('member', models.CharField(max_length=20)),
                ('process', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=20)),
                ('seq', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
