# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmeta',
            name='item',
            field=models.CharField(choices=[('a', 'ALL'), ('', 'None')], max_length=20),
        ),
        migrations.AlterField(
            model_name='urlmeta',
            name='market',
            field=models.CharField(choices=[('c', 'CCP'), ('T', 'TR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='urlmeta',
            name='process',
            field=models.CharField(choices=[('l', 'LIST'), ('D', 'DATA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='urlmeta',
            name='product',
            field=models.CharField(choices=[('iw', 'IRS-WON'), ('iu', 'IRS-USD'), ('nu', 'NDF-USD')], max_length=20),
        ),
    ]
