# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmeta',
            name='item',
            field=models.CharField(blank=True, choices=[('all', 'ALL'), (None, 'None')], max_length=20, null=True),
        ),
    ]
