# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IFD_POST_DATA_M_',
            new_name='IFD_POST_DATA_M',
        ),
        migrations.RenameModel(
            old_name='TOTAL_SEQ_INFO_M_',
            new_name='TOTAL_SEQ_INFO_M',
        ),
    ]
