# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0002_auto_20170907_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFD_BIZ_DATA_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.CharField(choices=[('ccp', 'CCP'), ('tr', 'TR')], max_length=20)),
                ('product', models.CharField(choices=[('irs-won', 'IRS-WON'), ('irs-usd', 'IRS-USD'), ('ndf', 'NDF')], max_length=20)),
                ('member', models.CharField(max_length=20)),
                ('item', models.CharField(blank=True, choices=[('tcpmih00101', 'TCPMIH00101'), ('tcpmih00102', 'TCPMIH00102'), ('tcpmih00103', 'TCPMIH00103'), ('tcpmih00104', 'TCPMIH00104'), ('tcpmih00105', 'TCPMIH00105'), ('tcpmih00106', 'TCPMIH00106'), ('tcpmih00107', 'TCPMIH00107'), ('tcpmir00101', 'TCPMIR00101')], max_length=20, null=True)),
                ('item_group', models.CharField(blank=True, choices=[('clearing', 'CLEARING'), ('settlement', 'SETTLEMENT'), ('risk', 'RISK'), ('pricing', 'PRICING'), ('rds', 'RDS'), ('post', 'POST')], max_length=20, null=True)),
                ('item_seq', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=2000)),
            ],
        ),
    ]
