# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0002_auto_20170424_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='irs_usd',
            field=models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='irs_won',
            field=models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='ndf',
            field=models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='pro_fx',
            field=models.CharField(choices=[('n', 'NO'), ('y', 'YES')], default='', max_length=3, null=True),
        ),
    ]
