# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0002_auto_20170422_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=20)),
                ('member', models.CharField(max_length=20)),
                ('bic_code', models.CharField(max_length=20)),
                ('lei_code', models.CharField(max_length=20)),
                ('member_name', models.CharField(max_length=20)),
                ('login_id', models.CharField(max_length=20)),
                ('login_pass', models.CharField(max_length=20)),
                ('irs_won', models.CharField(choices=[('y', 'YES'), ('n', 'NO')], max_length=1)),
                ('irs_usd', models.CharField(choices=[('y', 'YES'), ('n', 'NO')], max_length=1)),
                ('ndf', models.CharField(choices=[('y', 'YES'), ('n', 'NO')], max_length=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
