# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0003_memberinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberinfo',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='memberinfo',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
