# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0004_memberinfo_login_stat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberinfo',
            old_name='login_stat',
            new_name='login_state',
        ),
    ]
