# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0004_auto_20170424_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='market',
            field=models.CharField(choices=[('c', 'CCP'), ('T', 'TR')], max_length=20),
        ),
    ]
