# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0005_auto_20170831_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='login_state',
            field=models.CharField(max_length=3),
        ),
    ]
