# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0006_auto_20170424_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='irs_usd',
            field=models.CharField(choices=[('y', 'YES'), ('n', 'NO')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='irs_won',
            field=models.CharField(choices=[('y', 'YES'), ('n', 'NO')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='market',
            field=models.CharField(choices=[('c', 'CCP'), ('T', 'TR')], default='CCP', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='ndf',
            field=models.CharField(choices=[('y', 'YES'), ('n', 'NO')], max_length=3),
        ),
    ]
