#ccp/constant.py

# URL PATH MARKET/PRODUCT/MEMBER/PROCESS/ITEM/SEQ
# URL ex   ccp/IRS-WON/00002/LIST/ALL/00000000001
CHECK_OK      = "CHECK_OK"
CHECK_ERR_URL = "CHECK_ERROR_URL"
CHECK_MARKET  = "CHECK_MARKET"
CHECK_PRODUCT = "CHECK_PRODUCT"
CHECK_MEMBER  = "CHECK_MEMBER"
CHECK_DATE    = "CHECK_DATE"
CHECK_PROCESS = "CHECK_PROCESS"
CHECK_ITEM    = "CHECK_ITEM"
CHECK_SEQ     = "CHECK_SEQ"

# URS PATH ACCOUNTS
CHECK_ACCOUNTS= "CHECK_ACCOUNTS"
CHECK_USERNAME= "CHECK_USERNAME"
CHECK_PASSWORD= "CHECK_PASSWORD"


URL_MARKET_CCP      = "CCP"
URL_PRODUCT_IRS_WON = "IRS_WON"
URL_PRODUCT_IRS_USD = "IRS_USD"
URL_MARKET_MEMBER   = "URL_MEMBER"
URL_ITEM_LIST       = "LIST"
URL_ITEM_DATA       = "DATA"
URL_SEQ             = "URL_SEQ"


MARKET_CCP      = "ccp"
IRS_WON         = "irs_won"
IRS_USD         = "irs_usd"
NDF             = "ndf"
FX              = "fx"
