#ccp/constant.py

# URL PATH MARKET/PRODUCT/MEMBER/PROCESS/ITEM/SEQ
# URL ex   ccp/IRS-WON/00002/LIST/ALL/00000000001

CHECK_MARKET  = "CHECK_MARKET"
CHECK_PRODUCT = "CHECK_PRODUCT"
CHECK_MEMBER  = "CHECK_MEMBER"
CHECK_PROCESS = "CHECK_PROCESS"
CHECK_ITEM    = "CHECK_ITEM"
CHECK_SEQ     = "CHECK_SEQ"

URL_MARKET_CCP      = "CCP"
URL_PRODUCT_IRS_WON = "IRS_WON"
URL_PRODUCT_IRS_USD = "IRS_USD"
URL_MARKET_MEMBER   = "URL_MEMBER"
URL_ITEM_LIST       = "LIST"
URL_ITEM_DATA       = "DATA"
URL_SEQ             = "URL_SEQ"
